version: '3'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    # If you have other container dependencies or network configurations, add them here

volumes:
  jenkins_home:
    # You can specify a host path for persistence or use Docker-managed volumes
